[package]
name = "cargo-travis"
version = "0.0.1-pre0"
authors = ["roblabla <robinlambertz+dev@gmail.com>"]
description = "Run coverage, upload docs, and more on travis."
license = "MIT"

[dependencies]

cargo = "0.13.0"
rustc-serialize = "0.3"
